export const USER_ACTION_TYPES = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    CHECK_USER_SESSION : 'CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START : "EMAIL_SIGN_IN_START",
    EMAIL_SIGN_UP_START : "EMAIL_SIGN_UP_START",
    PROCESS_SUCCESS : "PROCESS_SUCCESS",
    PROCESS_FAILED : "PROCESS_FAILED",
    SIGN_OUT : "SIGN_OUT"

}