export const CategoryActionType = {
    FETCH_CATAGORIES_START: "FETCH_CATAGORIES_START",
    FETCH_CATAGORIES_SUCCESS: "FETCH_CATAGORIES_SUCCESS",
    FETCH_CATAGORIES_FAILED : "FETCH_CATAGORIES_FAILED"
}